name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v3

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 권한 부여 및 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # 테스트가 실패하면 배포가 안 되므로, 일단 테스트 제외(-x test)하고 빌드
        run: ./gradlew clean build -x test

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build & Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/studycafe-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/studycafe-app

      # 5. AWS EC2에 접속하여 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 최신 이미지 받기
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/studycafe-app
            
            # 기존 서버 멈추고 삭제 (없으면 에러 무시)
            sudo docker stop studycafe-server || true
            sudo docker rm studycafe-server || true
            
            # 새 서버 실행
            # --network="host" : EC2의 네트워크를 그대로 사용 (localhost가 EC2 자신이 됨 -> MySQL, Redis 연결 쉬워짐)
            sudo docker run -d --name studycafe-server \
              --network="host" \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/studycafe-app